import { Lead } from '@/types/lead';

export const mockLeads: Lead[] = [
  {
    id: 'lead-1',
    name: 'Sarah Jenkins',
    phone: '555-0101',
    email: 'sarah@example.com',
    project: 'Greenwood Residence',
    propertyType: 'Type 45',
    budget: '$500,000',
    message: 'I am interested in viewing a Type 45 unit this weekend.',
    source: 'Homepage',
    status: 'New',
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'lead-2',
    name: 'Michael Chen',
    phone: '555-0102',
    email: 'mchen@example.com',
    project: 'Grand Arunika',
    propertyType: 'Penthouse',
    budget: '$1,500,000+',
    message: 'Please send me the brochure for the new penthouse units.',
    source: 'Project Detail',
    status: 'Contacted',
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'lead-3',
    name: 'Amanda Brooks',
    phone: '555-0103',
    email: 'amanda.b@example.com',
    project: 'The Valley Estate',
    propertyType: 'Type 70',
    budget: '$750,000',
    message: 'Is there any unit available with a corner lot?',
    source: 'Property Detail',
    status: 'Qualified',
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'lead-4',
    name: 'James Wilson',
    phone: '555-0104',
    email: 'james.wilson@example.com',
    project: 'Greenwood Residence',
    propertyType: 'Type 36',
    budget: '$300,000',
    message: 'Looking for a starter home.',
    source: 'Campaign_FB',
    status: 'Lost',
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
  }
];
